

                                      _______________

                                         OmegaPlus
                                      _______________



 OmegaPlus version 3.0.0 released by Nikolaos Alachiotis and Pavlos Pavlidis in December 2014.


 Command:

	 omegaplus/OmegaPlus-G -name chr12.44313657.11.at.chr18.33.grid.run -input /home/kutsukos/synology/common/1KGP_phase3_data/ALL.chr18.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf -memLimit 15000 -minsnps 5 -gridFile gridListsCTRL//ctrl.chr18.33.grid -sampleList sampleLists/ERVtest.12.44313657.11.out -grid 420 -threads 16 -minwin 1000 -maxwin 50000 -seed 13124203



 Input file format (0:ms, 1:fasta, 2:macs, 3:vcf, 4:sf):	3
 Gap (-) imputation:						OFF
 Ambiguous character (N) imputation:				OFF
 Omega search strategy:						Exhaustive
 Alignment deduction to binary:					OFF
 Total number of samples in the VCF:				2504
 *** NOT FOUND: Sample "NA20344" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02363" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02377" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02381" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02024" does not exist in the VCF file ***
 *** NOT FOUND: Sample "NA19313" does not exist in the VCF file ***
 Samples excluded from the analysis:				2261


 Alignment 1
		Sequences:		486
		Sites:			2171507
		Discarded sites:	1302291

		Processing (seconds):	384.790627

		Max Omega:		26.359436
		Location:		39414904.00
		Leftmost SNP:		39413968
		Rightmost SNP:		39442864


 Total elapsed time 385.345843 seconds.


