

                                      _______________

                                         OmegaPlus
                                      _______________



 OmegaPlus version 3.0.0 released by Nikolaos Alachiotis and Pavlos Pavlidis in December 2014.


 Command:

	 omegaplus/OmegaPlus-G -name chr12.44313657.11.at.chr21.7.grid.run -input /home/kutsukos/synology/common/1KGP_phase3_data/ALL.chr21.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf -memLimit 15000 -minsnps 5 -gridFile gridListsCTRL//ctrl.chr21.7.grid -sampleList sampleLists/ERVtest.12.44313657.11.out -grid 420 -threads 16 -minwin 1000 -maxwin 50000 -seed 13124203



 Input file format (0:ms, 1:fasta, 2:macs, 3:vcf, 4:sf):	3
 Gap (-) imputation:						OFF
 Ambiguous character (N) imputation:				OFF
 Omega search strategy:						Exhaustive
 Alignment deduction to binary:					OFF
 Total number of samples in the VCF:				2504
 *** NOT FOUND: Sample "NA20344" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02363" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02377" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02381" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02024" does not exist in the VCF file ***
 *** NOT FOUND: Sample "NA19313" does not exist in the VCF file ***
 Samples excluded from the analysis:				2261


 Alignment 1
		Sequences:		486
		Sites:			1053876
		Discarded sites:	625055

		Processing (seconds):	186.936344

		Max Omega:		22.773975
		Location:		19307108.00
		Leftmost SNP:		19289573
		Rightmost SNP:		19308397


 Total elapsed time 187.402525 seconds.


