

                                      _______________

                                         OmegaPlus
                                      _______________



 OmegaPlus version 3.0.0 released by Nikolaos Alachiotis and Pavlos Pavlidis in December 2014.


 Command:

	 omegaplus/OmegaPlus-M -name chr12.44313657.11.at.chr1.10.grid.run -input /home/kutsukos/synology/common/1KGP_phase3_data/ALL.chr1.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf -minsnps 5 -gridFile gridListsCTRL/ctrl.chr1.10.grid -sampleList sampleLists/ERVtest.12.44313657.11.out -grid 420 -threads 16 -minwin 1000 -maxwin 50000 -seed 13124203



 Input file format (0:ms, 1:fasta, 2:macs, 3:vcf, 4:sf):	3
 Gap (-) imputation:						OFF
 Ambiguous character (N) imputation:				OFF
 Omega search strategy:						Exhaustive
 Alignment deduction to binary:					OFF
 Total number of samples in the VCF:				2504
 *** NOT FOUND: Sample "NA20344" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02363" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02377" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02381" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02024" does not exist in the VCF file ***
 *** NOT FOUND: Sample "NA19313" does not exist in the VCF file ***
 Samples excluded from the analysis:				2261


 Alignment 1
		Sequences:		486
		Sites:			6195844
		Discarded sites:	3745075

		Processing (seconds):	2458.983120

		Max Omega:		0.330237
		Location:		134194624.00
		Leftmost SNP:		121485079
		Rightmost SNP:		142536120


 Total elapsed time 2459.423475 seconds.


