

                                      _______________

                                         OmegaPlus
                                      _______________



 OmegaPlus version 3.0.0 released by Nikolaos Alachiotis and Pavlos Pavlidis in December 2014.


 Command:

	 omegaplus/OmegaPlus-G -name chr12.44313657.11.run -input /home/kutsukos/synology/common/1KGP_phase3_data/ALL.chr12.phase3_shapeit2_mvncall_integrated_v5a.20130502.genotypes.vcf -memLimit 15000 -minsnps 5 -gridFile gridLists/points.12.44063657.44563657.out -sampleList sampleLists/ERVtest.12.44313657.11.out -grid 420 -threads 2 -minwin 1000 -maxwin 50000 -seed 13124203



 Input file format (0:ms, 1:fasta, 2:macs, 3:vcf, 4:sf):	3
 Gap (-) imputation:						OFF
 Ambiguous character (N) imputation:				OFF
 Omega search strategy:						Exhaustive
 Alignment deduction to binary:					OFF
 Total number of samples in the VCF:				2504
 *** NOT FOUND: Sample "NA20344" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02363" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02377" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02381" does not exist in the VCF file ***
 *** NOT FOUND: Sample "HG02024" does not exist in the VCF file ***
 *** NOT FOUND: Sample "NA19313" does not exist in the VCF file ***
 Samples excluded from the analysis:				2261


 Alignment 1
		Sequences:		486
		Sites:			3697492
		Discarded sites:	2221917

		Processing (seconds):	1552.786997

		Max Omega:		16.745285
		Location:		44243656.00
		Leftmost SNP:		44242653
		Rightmost SNP:		44245366


 Total elapsed time 1553.703340 seconds.


